### ISSUE TITLE
enforce_migration_validations should support custom

### ISSUE THREAD

**Issue by singpolyma** [vprokopchuk256/mv-core#5]
This should be possible by catching the check constraint failure and turning it into a "is invalid" error instead of crashing the app

**Comment by vprokopchuk256** [comment]
@singpolyma  - not sure that it would be reasonable to handle an error AFTER real database operation. The main purpose of ```enforce_migration_validations``` is to define validations, not to handle db error. 

For example, if you define ```length``` constraint / validation at db level and call ```enforce_migration_validations``` on the corresponding ActiveRecord model then ActiveModel validation ```length``` would be defined. And validation is performed BEFORE database operation, so you can rely on ```valid?``` method. 

And such approach is not possible to implement ```custom``` validation because it's defined as database expression, not as ruby one. So - it's not possible to conduct ```custom``` validation when ```valid?``` method is called. 

At least I do not know how to do it and would be glad to hear any proposals if you have ones.

**Comment by singpolyma** [comment]
For sure, this would be a last-ditch sort of case and valid? would indeed be wrong, but errors could still be populated after save which is better than the app crashing? Or maybe not

**Comment by vprokopchuk256** [comment]
@singpolyma - oh. Looks like I see your point. You do not want to spread error handling between standard validation through ```valid?``` and database errors catching somewhere else. 

I would propose to define validation in the model that is equivalent to one defined in db. Let me illustrate this on example below. 

Let's imagine that you have custom db validation ( ```postgres``` in this case ) that checks attribute value against some regular expression: 

```
def up
    validates :posts, :content, custom: { statement: "TRIM({content}) ~ 'word'" }
end
```

Postgres driver error would be risen even if you add ```enforce_migration_validations``` into your ```ActiveRecord``` instance.

To avoid that you need to define equivalent validation in your ```ActiveRecord``` model instance. Something like that:

```
class Post
  enforce_migration_validators

  validates :content, with: /word/
end
```

```Migration Validators``` were designed to be an addition to ```ActiveModel``` validators. Not a replacement. And ```enforce_migration_validators``` macro was created to simplify defining ```ActiveModel``` validations based on ones defined in db. But it does not cover all cases. Some SQL <-> Ruby interpreter is required to cover custom validation. I do not know one and really appreciate if you know and recommend something.
